### ISSUE TITLE
File not exist

### ISSUE THREAD

**Issue by sevega** [PacktPublishing/Complete-Python-Course-with-10-Real-World-Projects#1]
In the chapter 14 you forgot tu put the file smallgray.png in the path and it don't exist in the compressed file.

**Comment by Sonakshis** [comment]
Hi,
The file **smallgray.png** is present in the code bundle. 

<img width="535" alt="Screenshot 2023-06-08 at 1 08 45 AM" src="https://github.com/PacktPublishing/Complete-Python-Course-with-10-Real-World-Projects/assets/85751562/74a7797a-d168-439c-8f32-07049b79fb7e">

<img width="545" alt="Screenshot 2023-06-08 at 1 09 15 AM" src="https://github.com/PacktPublishing/Complete-Python-Course-with-10-Real-World-Projects/assets/85751562/e799eef0-3b7c-4895-9514-950cb39cf95a">

<img width="541" alt="Screenshot 2023-06-08 at 1 10 15 AM" src="https://github.com/PacktPublishing/Complete-Python-Course-with-10-Real-World-Projects/assets/85751562/ab61d961-d90a-4421-9269-20c8fb65aa5b">

Happy Learning!
